spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jflow?characterEncoding=utf-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  global-config:
    db-config:
      id-type: AUTO

camunda.bpm:
  generic-properties.properties:
    javaSerializationFormatEnabled: true